-- MySQL Script generated by MySQL Workbench
-- Sat Jan 30 03:04:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cpg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpg` DEFAULT CHARACTER SET utf8 ;
USE `cpg` ;

-- -----------------------------------------------------
-- Table `cpg`.`experiencia_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia_tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo_experiencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`ciudad` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  UNIQUE INDEX `nombre_ciudad_UNIQUE` (`nombre_ciudad` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`establecimiento` (
  `id_establecimiento` INT NOT NULL AUTO_INCREMENT,
  `nit_establecimiento` BIGINT(20) NOT NULL,
  `nombre_establecimiento` VARCHAR(50) NOT NULL,
  `establecimiento_comercial` VARCHAR(60) NOT NULL,
  `correo_establecimiento` VARCHAR(60) NOT NULL,
  `celular_establecimiento` VARCHAR(10) NOT NULL,
  `direccion_establecimiento` VARCHAR(100) NOT NULL,
  `cantidad_lote` INT NOT NULL,
  `autorizacion_datos` TINYINT NOT NULL,
  `autorizacion_debito` TINYINT NOT NULL,
  `logo_establecimiento` VARCHAR(150) NULL,
  `estado_establecimiento` TINYINT NOT NULL DEFAULT 1,
  `ciudad_id_ciudad` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_establecimiento`),
  INDEX `fk_establecimiento_ciudad1_idx` (`ciudad_id_ciudad` ASC) VISIBLE,
  UNIQUE INDEX `nombre_empresa_UNIQUE` (`nombre_establecimiento` ASC) VISIBLE,
  UNIQUE INDEX `logo_establecimiento_UNIQUE` (`logo_establecimiento` ASC) VISIBLE,
  UNIQUE INDEX `correo_establecimiento_UNIQUE` (`correo_establecimiento` ASC) VISIBLE,
  UNIQUE INDEX `nit_UNIQUE` (`nit_establecimiento` ASC) VISIBLE,
  UNIQUE INDEX `id_establecimiento_UNIQUE` (`id_establecimiento` ASC) VISIBLE,
  CONSTRAINT `fk_establecimiento_ciudad1`
    FOREIGN KEY (`ciudad_id_ciudad`)
    REFERENCES `cpg`.`ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `titulo_experiencia` VARCHAR(150) NOT NULL,
  `descripcion_experiencia` VARCHAR(200) NOT NULL,
  `precio_experiencia` BIGINT(7) NOT NULL,
  `precio_publico` BIGINT(7) NOT NULL,
  `estado_experiencia` TINYINT NOT NULL DEFAULT 0,
  `comision` DECIMAL(5,2) NOT NULL,
  `imagen_experiencia` VARCHAR(150) NULL,
  `experiencia_tipo_id_tipo` INT NOT NULL,
  `id_establecimiento_experiencia` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_experiencia`),
  INDEX `fk_experiencia_experiencia_tipo1_idx` (`experiencia_tipo_id_tipo` ASC) VISIBLE,
  INDEX `fk_experiencia_establecimiento1_idx` (`id_establecimiento_experiencia` ASC) VISIBLE,
  UNIQUE INDEX `imagen_experiencia_UNIQUE` (`imagen_experiencia` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_experiencia_tipo1`
    FOREIGN KEY (`experiencia_tipo_id_tipo`)
    REFERENCES `cpg`.`experiencia_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_establecimiento1`
    FOREIGN KEY (`id_establecimiento_experiencia`)
    REFERENCES `cpg`.`establecimiento` (`id_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  `interfaz_movil` TINYINT NOT NULL,
  `interfaz_web` TINYINT NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `numero_identificacion` BIGINT(15) NULL,
  `email` VARCHAR(50) NOT NULL,
  `numero_celular` VARCHAR(10) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `estado_user` TINYINT NOT NULL DEFAULT 1,
  `usercol` VARCHAR(45) NULL,
  `rol_id_rol` INT NOT NULL DEFAULT 2,
  `id_establecimiento_user` INT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  `user_id_ciudad` INT NULL,
  `user_direccion` VARCHAR(400) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_rol1_idx` (`rol_id_rol` ASC) VISIBLE,
  INDEX `fk_user_establecimiento1_idx` (`id_establecimiento_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `cpg`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_establecimiento`
    FOREIGN KEY (`id_establecimiento_user`)
    REFERENCES `cpg`.`establecimiento` (`id_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`afiliacion` (
  `codigo_afiliacion` VARCHAR(8) NOT NULL,
  `codigo_asignado` TINYINT NOT NULL DEFAULT 0,
  `id_user_afiliacion` INT NULL,
  `fecha_activacion` DATETIME NULL,
  `fecha_vencimiento` DATETIME NULL,
  `fecha_expiracion` DATETIME NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`codigo_afiliacion`),
  INDEX `fk_afiliacion_user1_idx` (`id_user_afiliacion` ASC) VISIBLE,
  CONSTRAINT `fk_afiliacion_user1`
    FOREIGN KEY (`id_user_afiliacion`)
    REFERENCES `cpg`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`experiencia_usada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia_usada` (
  `id_experiencia_usada` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_user_experiencia_usada` INT NOT NULL,
  `id_experiencia_experiencia_usada` INT NOT NULL,
  `valor_comision` BIGINT(7) NOT NULL,
  `fecha_uso_experiencia_usada` DATETIME NOT NULL,
  `renovado_experiencia_usada` TINYINT NOT NULL DEFAULT 0,
  `cobrada_experiencia_usada` TINYINT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  INDEX `fk_experiencia_usada_experiencia1_idx` (`id_experiencia_experiencia_usada` ASC) VISIBLE,
  INDEX `fk_experiencia_usada_user1_idx` (`id_user_experiencia_usada` ASC) VISIBLE,
  PRIMARY KEY (`id_experiencia_usada`, `id_user_experiencia_usada`, `id_experiencia_experiencia_usada`),
  CONSTRAINT `fk_experiencia_usada_experiencia`
    FOREIGN KEY (`id_experiencia_experiencia_usada`)
    REFERENCES `cpg`.`experiencia` (`id_experiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_usada_user`
    FOREIGN KEY (`id_user_experiencia_usada`)
    REFERENCES `cpg`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `titulo_item` VARCHAR(100) NOT NULL,
  `descripcion_item` VARCHAR(800) NOT NULL,
  `estado_item` TINYINT NOT NULL DEFAULT 1,
  `experiencia_id_experiencia_item` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_item_experiencia1_idx` (`experiencia_id_experiencia_item` ASC) VISIBLE,
  CONSTRAINT `fk_item_experiencia1`
    FOREIGN KEY (`experiencia_id_experiencia_item`)
    REFERENCES `cpg`.`experiencia` (`id_experiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`util`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`util` (
  `id_param` INT NOT NULL,
  `nombre_param` VARCHAR(45) NOT NULL,
  `valor_param` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_param`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`historico_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`historico_establecimiento` (
  `id_establecimiento_historico` INT NOT NULL,
  `procesados_total` INT NOT NULL DEFAULT 0,
  `procesados_lote` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_establecimiento_historico`),
  CONSTRAINT `fk_historico_establecimiento`
    FOREIGN KEY (`id_establecimiento_historico`)
    REFERENCES `cpg`.`establecimiento` (`id_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`periodo_afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`periodo_afiliacion` (
  `afiliacion_codigo_afiliacion` VARCHAR(8) NOT NULL,
  `periodo_afiliacion` INT NOT NULL,
  `fecha_afiliacion` DATETIME NOT NULL,
  PRIMARY KEY (`afiliacion_codigo_afiliacion`, `periodo_afiliacion`),
  INDEX `fk_periodo_afiliacion_afiliacion1_idx` (`afiliacion_codigo_afiliacion` ASC) VISIBLE,
  CONSTRAINT `fk_periodo_afiliacion_afiliacion1`
    FOREIGN KEY (`afiliacion_codigo_afiliacion`)
    REFERENCES `cpg`.`afiliacion` (`codigo_afiliacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`noticia` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo_noticia` VARCHAR(100) NOT NULL,
  `contenido_noticia` VARCHAR(1000) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NULL,
  `imagen_noticia` VARCHAR(100) NULL,
  `estado_noticia` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_noticia`))
ENGINE = InnoDB
AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `cpg`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`tarjeta` (
  `id_tarjeta` VARCHAR(200) NOT NULL,
  `numero_tarjeta` VARCHAR(16) NOT NULL,
  `cvc` VARCHAR(3) NOT NULL,
  `exp_month` VARCHAR(2) NOT NULL,
  `exp_year` VARCHAR(2) NOT NULL,
  `card_holder` VARCHAR(100) NOT NULL,
  `created_at` VARCHAR(200) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_four` VARCHAR(4) NOT NULL,
  `bin` BIGINT(10) NOT NULL,
  `expires_at` VARCHAR(100) NOT NULL,
  `estado_tarjeta` TINYINT NOT NULL DEFAULT 1,
  `id_establecimiento_tarjeta` INT NOT NULL,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `fk_tarjeta_establecimiento1_idx` (`id_establecimiento_tarjeta` ASC) VISIBLE,
  CONSTRAINT `fk_tarjeta_establecimiento1`
    FOREIGN KEY (`id_establecimiento_tarjeta`)
    REFERENCES `cpg`.`establecimiento` (`id_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`fuente_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`fuente_pago` (
  `id_fuente_pago` BIGINT(10) NOT NULL,
  `acceptance_token` VARCHAR(1000) NOT NULL,
  `customer_email` VARCHAR(500) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `id_tarjeta_fuente_pago` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_fuente_pago`),
  INDEX `fk_fuente_pago_tarjeta1_idx` (`id_tarjeta_fuente_pago` ASC) VISIBLE,
  CONSTRAINT `fk_fuente_pago_tarjeta1`
    FOREIGN KEY (`id_tarjeta_fuente_pago`)
    REFERENCES `cpg`.`tarjeta` (`id_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`pago` (
  `id_pago` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `total_monto` BIGINT(10) NOT NULL,
  `id_establecimiento_pago` INT NOT NULL,
  `pago_aceptado` TINYINT NULL,
  `fuente_pago_id_fuente_pago` BIGINT(10) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL,
  `id_transaction` VARCHAR(100) NULL,
  `observacion_pago` VARCHAR(100) NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_establecimiento1_idx` (`id_establecimiento_pago` ASC) VISIBLE,
  INDEX `fk_pago_fuente_pago1_idx` (`fuente_pago_id_fuente_pago` ASC) VISIBLE,
  CONSTRAINT `fk_pago_establecimiento1`
    FOREIGN KEY (`id_establecimiento_pago`)
    REFERENCES `cpg`.`establecimiento` (`id_establecimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_fuente_pago1`
    FOREIGN KEY (`fuente_pago_id_fuente_pago`)
    REFERENCES `cpg`.`fuente_pago` (`id_fuente_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
