-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 19:33:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cpg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cpg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cpg` DEFAULT CHARACTER SET utf8 ;
USE `cpg` ;

-- -----------------------------------------------------
-- Table `cpg`.`experiencia_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia_tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `tipo_experiencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`ciudad` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre_ciudad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  UNIQUE INDEX `nombre_ciudad_UNIQUE` (`nombre_ciudad` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`establecimiento` (
  `nit` BIGINT(20) NOT NULL,
  `nombre_empresa` VARCHAR(50) NOT NULL,
  `establecimiento_comercial` VARCHAR(60) NOT NULL,
  `correo_establecimiento` VARCHAR(60) NOT NULL,
  `celular_establecimiento` VARCHAR(10) NOT NULL,
  `direccion_establecimiento` VARCHAR(100) NOT NULL,
  `cantidad_lote` INT NOT NULL,
  `autorizacion_datos` TINYINT NOT NULL,
  `autorizacion_debito` TINYINT NOT NULL,
  `logo_establecimiento` VARCHAR(150) NULL,
  `estado_establecimiento` TINYINT NOT NULL DEFAULT 1,
  `ciudad_id_ciudad` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`nit`),
  INDEX `fk_establecimiento_ciudad1_idx` (`ciudad_id_ciudad` ASC) VISIBLE,
  UNIQUE INDEX `nombre_empresa_UNIQUE` (`nombre_empresa` ASC) VISIBLE,
  UNIQUE INDEX `logo_establecimiento_UNIQUE` (`logo_establecimiento` ASC) VISIBLE,
  UNIQUE INDEX `correo_establecimiento_UNIQUE` (`correo_establecimiento` ASC) VISIBLE,
  CONSTRAINT `fk_establecimiento_ciudad1`
    FOREIGN KEY (`ciudad_id_ciudad`)
    REFERENCES `cpg`.`ciudad` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `titulo_experiencia` VARCHAR(150) NOT NULL,
  `descripcion_experiencia` VARCHAR(200) NOT NULL,
  `precio_experiencia` BIGINT(7) NOT NULL,
  `precio_publico` BIGINT(7) NOT NULL,
  `estado_experiencia` TINYINT NOT NULL DEFAULT 0,
  `comision` DECIMAL(5,2) NOT NULL,
  `imagen_experiencia` VARCHAR(150) NULL,
  `experiencia_tipo_id_tipo` INT NOT NULL,
  `establecimiento_nit` BIGINT(20) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_experiencia`),
  INDEX `fk_experiencia_experiencia_tipo1_idx` (`experiencia_tipo_id_tipo` ASC) VISIBLE,
  INDEX `fk_experiencia_establecimiento1_idx` (`establecimiento_nit` ASC) VISIBLE,
  UNIQUE INDEX `imagen_experiencia_UNIQUE` (`imagen_experiencia` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_experiencia_tipo1`
    FOREIGN KEY (`experiencia_tipo_id_tipo`)
    REFERENCES `cpg`.`experiencia_tipo` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_establecimiento1`
    FOREIGN KEY (`establecimiento_nit`)
    REFERENCES `cpg`.`establecimiento` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `numero_identificacion` BIGINT(15) NULL,
  `email` VARCHAR(50) NOT NULL,
  `numero_celular` VARCHAR(10) NOT NULL,
  `password` VARCHAR(1000) NOT NULL,
  `estado_user` TINYINT NOT NULL DEFAULT 1,
  `rol_id_rol` INT NOT NULL DEFAULT 2,
  `establecimiento_nit_user` BIGINT(20) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_rol1_idx` (`rol_id_rol` ASC) VISIBLE,
  INDEX `fk_user_establecimiento1_idx` (`establecimiento_nit_user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `cpg`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_establecimiento1`
    FOREIGN KEY (`establecimiento_nit_user`)
    REFERENCES `cpg`.`establecimiento` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`afiliacion` (
  `codigo_afiliacion` VARCHAR(8) NOT NULL,
  `asignada` TINYINT NOT NULL DEFAULT 0,
  `user_id_user` INT NULL,
  `fecha_uso` DATETIME NULL,
  `fecha_vencimiento` DATETIME NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`codigo_afiliacion`),
  INDEX `fk_afiliacion_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_afiliacion_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `cpg`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`experiencia_usada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`experiencia_usada` (
  `id_experiencia_usada` INT NOT NULL AUTO_INCREMENT,
  `user_id_user_usada` INT NOT NULL,
  `experiencia_id_experiencia_usada` INT NOT NULL,
  `fecha_uso_experiencia_usada` DATETIME NOT NULL,
  `renovado_experiencia_usada` TINYINT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  INDEX `fk_experiencia_usada_experiencia1_idx` (`experiencia_id_experiencia_usada` ASC) VISIBLE,
  INDEX `fk_experiencia_usada_user1_idx` (`user_id_user_usada` ASC) VISIBLE,
  PRIMARY KEY (`id_experiencia_usada`, `user_id_user_usada`, `experiencia_id_experiencia_usada`),
  CONSTRAINT `fk_experiencia_usada_experiencia1`
    FOREIGN KEY (`experiencia_id_experiencia_usada`)
    REFERENCES `cpg`.`experiencia` (`id_experiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_usada_user1`
    FOREIGN KEY (`user_id_user_usada`)
    REFERENCES `cpg`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `titulo_item` VARCHAR(100) NOT NULL,
  `descripcion_item` VARCHAR(800) NOT NULL,
  `estado_item` TINYINT NOT NULL DEFAULT 1,
  `experiencia_id_experiencia_item` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_item_experiencia1_idx` (`experiencia_id_experiencia_item` ASC) VISIBLE,
  CONSTRAINT `fk_item_experiencia1`
    FOREIGN KEY (`experiencia_id_experiencia_item`)
    REFERENCES `cpg`.`experiencia` (`id_experiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`util`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`util` (
  `id_param` INT NOT NULL,
  `nombre_param` VARCHAR(45) NOT NULL,
  `valor_param` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_param`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`historico_establecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`historico_establecimiento` (
  `establecimiento_nit_historico` BIGINT(20) NOT NULL,
  `procesados_total` INT NOT NULL DEFAULT 0,
  `procesados_lote` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`establecimiento_nit_historico`),
  CONSTRAINT `fk_historico_establecimiento_establecimiento1`
    FOREIGN KEY (`establecimiento_nit_historico`)
    REFERENCES `cpg`.`establecimiento` (`nit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cpg`.`periodo_afiliacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cpg`.`periodo_afiliacion` (
  `afiliacion_codigo_afiliacion` VARCHAR(8) NOT NULL,
  `periodo_afiliacion` INT NOT NULL,
  `fecha_afiliacion` DATETIME NOT NULL,
  PRIMARY KEY (`afiliacion_codigo_afiliacion`, `periodo_afiliacion`),
  INDEX `fk_periodo_afiliacion_afiliacion1_idx` (`afiliacion_codigo_afiliacion` ASC) VISIBLE,
  CONSTRAINT `fk_periodo_afiliacion_afiliacion1`
    FOREIGN KEY (`afiliacion_codigo_afiliacion`)
    REFERENCES `cpg`.`afiliacion` (`codigo_afiliacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
